; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-touch-amoled]
; Force the use of the latest platform version that supports OPI bootloaders
;platform = espressif32 @ ^6.7.0
;platform = https://github.com/platformio/platform-espressif32.git
;platform = espressif32
;platform = espressif32 @ 6.12.0 ;Overcome esp32-hal-periman.h compile error by forcing latest ESP32 Arduino 3.0 core, vs PlatformIO's stable version of 2.x
;platform = https://github.com/platformio/platform-espressif32.git ;Fixes above + PlatformIO "Espressif32" platform (6.12.0) doesn't know that Arduino 3.0 split its files into two separate packages. It's looking for a folder called libs that doesn't exist in the old structure. To fix this, we need to move to the development version of the PlatformIO Espressif32 platform, which was specifically updated to handle this new Arduino 3.0 file structure.
platform = espressif32 @ 6.6.0 ;specific stable version without Arduino 3.0 specific metadata bugs
board = esp32-s3-devkitc-1
framework = arduino

; FORCE PlatformIO to use the stable 2.0.x framework instead of 3.x
platform_packages =
    framework-arduinoespressif32 @ ~3.20017.0

; Your board uses the ESP32-S3R8 (8MB PSRAM)
board_build.arduino.memory_type = qio_opi
;board_build.flash_mode = qio ; Change flash_mode to qio to satisfy esptool
; try to overcome boot issue
board_build.flash_mode = dio
board_build.psram_type = opi

; Flash size is 32MB according to Waveshare specs
board_upload.flash_size = 32MB
; Force flash frequency to 80MHz to match your hardware
board_build.f_flash = 80000000L
;board_build.f_flash = 40000000L

; Necessary build flags for the S3 chip and PSRAM
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_GFX_CLOCK_SPEED=20000000L  ; Force 20MHz for stability

monitor_port = COM3
monitor_speed = 115200

; lib_deps =
;     https://github.com/moononournation/Arduino_GFX.git#v1.4.9
;     https://github.com/lewisxhe/SensorLib.git
;     https://github.com/lewisxhe/XPowersLib.git

lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.4.9
    lewisxhe/XPowersLib @ ^0.2.6
    lewisxhe/SensorLib @ ^0.3.1