[env:esp32-s3-touch-amoled]
platform = espressif32@6.5.0  ; Stable version before the 'periman' break
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio

lib_deps =
    ;moononournation/GFX Library for Arduino @ 1.4.7
    https://github.com/moononournation/Arduino_GFX.git#v1.4.7
    lewisxhe/XPowersLib @ 0.2.6

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1