[env:esp32-s3-touch-amoled]
platform = espressif32@6.6.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi ; Critical for the AMOLED version
board_build.f_flash = 80000000L
board_build.flash_mode = qio

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1

lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.4.9
    lewisxhe/XPowersLib @ ^0.2.6
    lewisxhe/SensorLib @ ^0.3.1